# AGENT FOR LLAMAINDEX
#LLM: 'starling-lm:7b-alpha-q4_K_M'
LLM: 'starling-lm:7b-alpha-q5_K_M'
#LLM: 'adrienbrault/nous-hermes2pro:Q5_K_M-json'
EMBEDDINGS: 'sentence-transformers/all-mpnet-base-v2'
WEAVIATE_URL: 'http://localhost:8080'
CHUNK_SIZE: 3000
OLLAMA_BASE_URL: 'http://127.0.0.1:11434'
#OLLAMA_BASE_URL: 'http://192.168.68.107:11434'


# AGENT FOR HAYSTACK
SPLIT_BY_HAYSTACK: 'sentence'
SPLIT_LENGTH_HAYSTACK: 10
SPLIT_OVERLAP_HAYSTACK: 2
EMBEDDINGS_HAYSTACK: 'sentence-transformers/all-MiniLM-L6-v2'
#LLM_HAYSTACK: 'starling-lm:7b-alpha-q4_K_M'
LLM_HAYSTACK: 'starling-lm:7b-alpha-q5_K_M'
#LLM_HAYSTACK: 'adrienbrault/nous-hermes2pro:Q5_K_M-json'
OLLAMA_BASE_URL_HAYSTACK: 'http://127.0.0.1:11434'
#OLLAMA_BASE_URL_HAYSTACK: 'http://192.168.68.107:11434'
MAX_LOOPS_ALLOWED_HAYSTACK: 3


# AGENT FOR VLLAMAINDEX
LLM_VLLAMAINDEX: 'llava:13b'


# AGENT FOR VPROCESSOR
VPROCESSOR_OCR_ENDPOINT: 'http://127.0.0.1:8001/api/v1/vessel-ocr/inference'
LLM_VPROCESSOR: 'starling-lm:7b-alpha-q5_K_M'
#LLM_VPROCESSOR: 'adrienbrault/nous-hermes2pro:Q5_K_M-json'
OLLAMA_BASE_URL_VPROCESSOR: 'http://127.0.0.1:11434'


# AGENT FOR FUNCTION CALL
OLLAMA_BASE_URL_FUNCTION: 'http://127.0.0.1:11434/v1'
LLM_FUNCTION: 'starling-lm:7b-alpha-q5_K_M'
