LLM_FUNCTION: adrienbrault/nous-hermes2theta-llama3-8b:q5_K_M
OLLAMA_BASE_URL_FUNCTION: http://127.0.0.1:11434/v1

PROTECTED_ACCESS: false
SPARROW_KEYS:
  key1:
    usage_count: 0
    usage_limit: 5
    value: value1
  key2:
    usage_count: 0
    usage_limit: 3
    value: value2
